# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='docfile',
            field=models.FileField(default=1, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
