# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fries', '0002_user_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='docfile',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
