# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import fries.models


class Migration(migrations.Migration):

    dependencies = [
        ('fries', '0003_auto_20171026_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to=fries.models.user_directory_path),
        ),
    ]
